name: tekartik_prefs
description: Common prefs interface
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  synchronized:
  cv: ">=1.1.8"
dev_dependencies:
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: any
  build_web_compilers: ">=4.0.11"
  process_run: ">=1.2.1+1"
resolution: workspace
